"""empty message

Revision ID: 1520f30f64d9
Revises: 37440fe6a687
Create Date: 2022-08-04 19:46:53.421033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1520f30f64d9'
down_revision = '37440fe6a687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_poke',
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('user_pokemon_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pokemon', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_pokemon_fkey', 'user', 'pokemon', ['pokemon'], ['id'])
    op.drop_table('user_poke')
    # ### end Alembic commands ###
