"""empty message

Revision ID: 37440fe6a687
Revises: 86591d921ad6
Create Date: 2022-08-04 19:34:29.054550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37440fe6a687'
down_revision = '86591d921ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pokemon', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'pokemon', ['pokemon'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'pokemon')
    # ### end Alembic commands ###
