"""empty message

Revision ID: 86591d921ad6
Revises: d5c7e7b76f27
Create Date: 2022-08-04 19:27:16.438651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86591d921ad6'
down_revision = 'd5c7e7b76f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('ability', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('base_experience', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('attack_base_stat', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('hp_base_stat', sa.String(), nullable=True))
    op.add_column('pokemon', sa.Column('defense_stat', sa.String(), nullable=True))
    op.drop_constraint('pokemon_name_key', 'pokemon', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pokemon_name_key', 'pokemon', ['name'])
    op.drop_column('pokemon', 'defense_stat')
    op.drop_column('pokemon', 'hp_base_stat')
    op.drop_column('pokemon', 'attack_base_stat')
    op.drop_column('pokemon', 'base_experience')
    op.drop_column('pokemon', 'ability')
    # ### end Alembic commands ###
