"""empty message

Revision ID: 90591ca198e9
Revises: c3b626bb9c29
Create Date: 2022-08-04 16:26:42.040541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90591ca198e9'
down_revision = 'c3b626bb9c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pokemon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'pokemon', ['pokemon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'pokemon_id')
    # ### end Alembic commands ###
